# Pandas Tutorial

### Data Merging

#### Joins

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Aarav", "Sita", "Rohan"]
})

df2 = pd.DataFrame({
    "ID": [1, 2, 4],
    "Marks": [85, 90, 78]
})

In [2]:
pd.merge(df1, df2, on="ID", how="inner")

   ID   Name  Marks
0   1  Aarav     85
1   2   Sita     90

In [3]:
pd.concat([df1, df2], axis=1)

   ID   Name  ID  Marks
0   1  Aarav   1     85
1   2   Sita   2     90
2   3  Rohan   4     78

In [4]:
df1["ID"].is_unique

True

In [6]:
df1 = df1.drop_duplicates(subset="ID")
df1

   ID   Name
0   1  Aarav
1   2   Sita
2   3  Rohan