# Pandas Tutorial

### Data Wrangling

In [15]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("amazon.csv")
df.loc[0:2, ["product_name", "category"]]  # Inclusive

,product_name,category
0,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...
1,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...
2,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...

In [6]:
df.iloc[0:2, 1:3]

,product_name,category
0,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...
1,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...

In [9]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Aarav", "Sita", "Rohan", "Meera", "Anil"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 92, 78, 88, 95],
    "City": ["Kathmandu", "Lalitpur", "Bhaktapur", "Kathmandu", "Pokhara"],
    "Gender": ["M", "F", "M", "F", "M"]
}

df = pd.DataFrame(data)

In [10]:
df["Marks"].apply(lambda x: x + 5)

0     90
1     97
2     83
3     93
4    100
Name: Marks, dtype: int64

In [11]:
df.apply(lambda row: row["Marks"] + row["Age"], axis=1)

0    105
1    113
2     97
3    110
4    115
dtype: int64

In [12]:
df["Gender"].map({"M": "Male", "F": "Female"})

0      Male
1    Female
2      Male
3    Female
4      Male
Name: Gender, dtype: object

In [13]:
df["Percentage"] = (df["Marks"] / 100) * 100

In [14]:
df

   Student_ID   Name  Age  Marks       City Gender  Percentage
0         101  Aarav   20     85  Kathmandu      M        85.0
1         102   Sita   21     92   Lalitpur      F        92.0
2         103  Rohan   19     78  Bhaktapur      M        78.0
3         104  Meera   22     88  Kathmandu      F        88.0
4         105   Anil   20     95    Pokhara      M        95.0

In [16]:
df["Result"] = np.where(df["Marks"] >= 40, "Pass", "Fail")

In [17]:
df

   Student_ID   Name  Age  Marks       City Gender  Percentage Result
0         101  Aarav   20     85  Kathmandu      M        85.0   Pass
1         102   Sita   21     92   Lalitpur      F        92.0   Pass
2         103  Rohan   19     78  Bhaktapur      M        78.0   Pass
3         104  Meera   22     88  Kathmandu      F        88.0   Pass
4         105   Anil   20     95    Pokhara      M        95.0   Pass

#### String Operations

In [ ]:
df["Name"].str.lower()

In [20]:
df[df["City"].str.contains("Kathmandu")]

   Student_ID   Name  Age  Marks       City Gender  Percentage Result
0         101  Aarav   20     85  Kathmandu      M        85.0   Pass
3         104  Meera   22     88  Kathmandu      F        88.0   Pass

In [24]:
dates = pd.DataFrame({
    "Date": ["2024-01-01", "2024-02-15", "2024-03-10"]
})

dates["Date"] = pd.to_datetime(dates["Date"])

In [27]:
dates["Year"] = dates["Date"].dt.year
dates["Weekday"] = dates["Date"].dt.day_name()
dates

        Date  Year   Weekday
0 2024-01-01  2024    Monday
1 2024-02-15  2024  Thursday
2 2024-03-10  2024    Sunday