# Pandas Tutorial

### Advanced Concepts

#### Windows

In [2]:
import pandas as pd

In [6]:
sales = pd.Series([10, 20, 30, 40])
sales.rolling(window=3).mean()

0     NaN
1     NaN
2    20.0
3    30.0
dtype: float64

In [10]:
print(sales.rolling(window=3).sum())
print(sales.rolling(window=3).max())
print(sales.rolling(window=3).min())

0     NaN
1     NaN
2    60.0
3    90.0
dtype: float64
0     NaN
1     NaN
2    30.0
3    40.0
dtype: float64
0     NaN
1     NaN
2    10.0
3    20.0
dtype: float64

In [11]:
sales.expanding().mean()

0    10.0
1    15.0
2    20.0
3    25.0
dtype: float64

In [12]:
df = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Aarav", "Sita", "Rohan"]
})

df.memory_usage()

Index    132
ID        24
Name      24
dtype: int64

In [13]:
df.memory_usage(deep=True)

Index    132
ID        24
Name     161
dtype: int64

In [14]:
df.memory_usage(deep=True).sum()

np.int64(317)

In [15]:
data = {
    "Region": ["East", "East", "West", "West"],
    "City": ["Kathmandu", "Lalitpur", "Pokhara", "Butwal"],
    "Sales": [100, 200, 300, 400]
}

df = pd.DataFrame(data)
df

  Region       City  Sales
0   East  Kathmandu    100
1   East   Lalitpur    200
2   West    Pokhara    300
3   West     Butwal    400

In [17]:
df_multi = df.set_index(["Region", "City"])
df_multi

                  Sales
Region City
East   Kathmandu    100
       Lalitpur     200
West   Pokhara      300
       Butwal       400

In [19]:
import numpy as np

data = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Name": ["Aarav", "Sita", "Rohan", "Meera", "Anil", "Kiran"],
    "Age": [20, 21, 19, 22, 20, 23],
    "Marks": [85, 92, 78, 88, 95, 60],
    "City": ["Kathmandu", "Lalitpur", "Pokhara", "Kathmandu", "Butwal", "Pokhara"],
    "Gender": ["M", "F", "M", "F", "M", "M"],
    "Join_Date": ["2024-01-01", "2024-02-15", "2024-03-10", "2024-01-20", "2024-05-01", "2024-06-01"]
}

df = pd.DataFrame(data)

In [20]:
df.query("Marks > 80")

   ID   Name  Age  Marks       City Gender   Join_Date
0   1  Aarav   20     85  Kathmandu      M  2024-01-01
1   2   Sita   21     92   Lalitpur      F  2024-02-15
3   4  Meera   22     88  Kathmandu      F  2024-01-20
4   5   Anil   20     95     Butwal      M  2024-05-01

In [21]:
df.query("Marks > 80 and Age < 22")

   ID   Name  Age  Marks       City Gender   Join_Date
0   1  Aarav   20     85  Kathmandu      M  2024-01-01
1   2   Sita   21     92   Lalitpur      F  2024-02-15
4   5   Anil   20     95     Butwal      M  2024-05-01

In [22]:
df.query("Marks > 90 or Age == 19")

   ID   Name  Age  Marks      City Gender   Join_Date
1   2   Sita   21     92  Lalitpur      F  2024-02-15
2   3  Rohan   19     78   Pokhara      M  2024-03-10
4   5   Anil   20     95    Butwal      M  2024-05-01

In [23]:
min_marks = 80

df.query("Marks > @min_marks")

   ID   Name  Age  Marks       City Gender   Join_Date
0   1  Aarav   20     85  Kathmandu      M  2024-01-01
1   2   Sita   21     92   Lalitpur      F  2024-02-15
3   4  Meera   22     88  Kathmandu      F  2024-01-20
4   5   Anil   20     95     Butwal      M  2024-05-01

In [24]:
df.query("Name == 'Aarav'")

   ID   Name  Age  Marks       City Gender   Join_Date
0   1  Aarav   20     85  Kathmandu      M  2024-01-01